param(
  [string]$RootDir,
  [string]$EmitEnvFile,
  [switch]$Quiet
)

$ErrorActionPreference = 'Stop'

if (-not $RootDir) {
  $RootDir = $PSScriptRoot
}

function Write-Log {
  param([string]$Message)
  if (-not $Quiet) {
    Write-Host $Message
  }
}

function Ensure-Dir {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path | Out-Null
  }
}

function Get-CommandPathOrNull {
  param([string]$Command)
  try {
    return (Get-Command $Command -ErrorAction Stop).Source
  } catch {
    return $null
  }
}

function Invoke-Download {
  param(
    [string]$Url,
    [string]$OutFile
  )
  $ua = @{
    'User-Agent' = 'NvlabKimodoQuickServer-Bootstrap'
  }
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  Invoke-WebRequest -Uri $Url -OutFile $OutFile -UseBasicParsing -Headers $ua
}

function Get-GitLfsDownloadUrl {
  $releaseApi = 'https://api.github.com/repos/git-lfs/git-lfs/releases/latest'
  $ua = @{
    'User-Agent' = 'NvlabKimodoQuickServer-Bootstrap'
  }
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  $release = Invoke-RestMethod -Uri $releaseApi -Headers $ua
  $asset = $release.assets |
    Where-Object { $_.name -match '^git-lfs-windows-amd64-v.*\.zip$' } |
    Select-Object -First 1
  if (-not $asset) {
    throw 'No git-lfs windows amd64 zip asset found in latest release.'
  }
  return $asset.browser_download_url
}

function Get-MinGitDownloadUrl {
  $releaseApi = 'https://api.github.com/repos/git-for-windows/git/releases/latest'
  $ua = @{
    'User-Agent' = 'NvlabKimodoQuickServer-Bootstrap'
  }
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  $release = Invoke-RestMethod -Uri $releaseApi -Headers $ua
  $asset = $release.assets |
    Where-Object { $_.name -match '^MinGit-.*-64-bit\.zip$' } |
    Select-Object -First 1
  if (-not $asset) {
    throw 'No MinGit 64-bit zip asset found in latest release.'
  }
  return $asset.browser_download_url
}

function Emit-EnvFile {
  param(
    [string]$Path,
    [string[]]$ExtraPaths
  )
  if (-not $Path) {
    return
  }

  $valid = @()
  foreach ($p in $ExtraPaths) {
    if ($p -and (Test-Path -LiteralPath $p)) {
      $valid += $p
    }
  }

  $envLine = if ($valid.Count -gt 0) {
    'set "PATH=' + (($valid -join ';') + ';%PATH%') + '"'
  } else {
    'rem no extra path entries required'
  }

  $content = @(
    '@echo off',
    'rem generated by ensure_portable_git_lfs.ps1',
    $envLine
  )

  $parent = Split-Path -Parent $Path
  if ($parent) {
    Ensure-Dir -Path $parent
  }
  Set-Content -Path $Path -Value $content -Encoding Ascii
}

$isWindows = $env:OS -eq 'Windows_NT'
$toolsDir = Join-Path $RootDir 'tools'
$portableGitDir = Join-Path $toolsDir 'PortableGit'
$portableGitCmd = Join-Path $portableGitDir 'cmd'
$portableGitMingwBin = Join-Path $portableGitDir 'mingw64\bin'
$portableLfsBin = $portableGitMingwBin
$portableGitExe = Join-Path $portableGitCmd 'git.exe'
$portableLfsExe = Join-Path $portableLfsBin 'git-lfs.exe'

$gitCmd = Get-CommandPathOrNull -Command 'git'
$lfsCmd = Get-CommandPathOrNull -Command 'git-lfs'

if (-not $gitCmd -and -not $isWindows) {
  throw 'git is missing and auto portable install is only implemented for Windows. On Linux, install git + git-lfs first.'
}

if (-not $gitCmd -and $isWindows) {
  Write-Log '[STEP] git not found, installing local portable git...'
  Ensure-Dir -Path $toolsDir

  $downloadDir = Join-Path $toolsDir 'downloads'
  Ensure-Dir -Path $downloadDir

  $gitZip = Join-Path $downloadDir 'MinGit-64-bit.zip'
  $tmpExtract = Join-Path $downloadDir ('MinGit_extract_' + [Guid]::NewGuid().ToString('N'))
  Ensure-Dir -Path $tmpExtract

  $minGitUrl = Get-MinGitDownloadUrl
  Invoke-Download -Url $minGitUrl -OutFile $gitZip
  Expand-Archive -Path $gitZip -DestinationPath $tmpExtract -Force

  if (Test-Path -LiteralPath $portableGitDir) {
    $bak = $portableGitDir + '.bak.' + (Get-Date -Format 'yyyyMMddHHmmss')
    Move-Item -LiteralPath $portableGitDir -Destination $bak
  }

  New-Item -ItemType Directory -Path $portableGitDir | Out-Null
  Copy-Item -Path (Join-Path $tmpExtract '*') -Destination $portableGitDir -Recurse -Force
}

if (-not $lfsCmd -and $isWindows) {
  Write-Log '[STEP] git-lfs not found, installing local git-lfs...'
  Ensure-Dir -Path $toolsDir

  $downloadDir = Join-Path $toolsDir 'downloads'
  Ensure-Dir -Path $downloadDir

  $lfsZip = Join-Path $downloadDir 'git-lfs-windows-amd64.zip'
  $tmpExtract = Join-Path $downloadDir ('gitlfs_extract_' + [Guid]::NewGuid().ToString('N'))
  Ensure-Dir -Path $tmpExtract

  $lfsUrl = Get-GitLfsDownloadUrl
  Invoke-Download -Url $lfsUrl -OutFile $lfsZip
  Expand-Archive -Path $lfsZip -DestinationPath $tmpExtract -Force

  $lfsBinSource = Get-ChildItem -Path $tmpExtract -Recurse -Filter 'git-lfs.exe' | Select-Object -First 1
  if (-not $lfsBinSource) {
    throw 'git-lfs.exe not found after extraction.'
  }

  Ensure-Dir -Path $portableLfsBin
  Copy-Item -LiteralPath $lfsBinSource.FullName -Destination $portableLfsExe -Force
}

$pathsToAdd = @()
if (Test-Path -LiteralPath $portableGitCmd) {
  $pathsToAdd += $portableGitCmd
}
if (Test-Path -LiteralPath $portableGitMingwBin) {
  $pathsToAdd += $portableGitMingwBin
}
if (Test-Path -LiteralPath $portableLfsBin) {
  $pathsToAdd += $portableLfsBin
}

if ($pathsToAdd.Count -gt 0) {
  $env:PATH = ($pathsToAdd -join ';') + ';' + $env:PATH
}

if (-not (Get-CommandPathOrNull -Command 'git')) {
  throw 'git is still unavailable after bootstrap.'
}

$gitLfsOk = $false
try {
  $null = & git lfs version
  $gitLfsOk = $true
} catch {
  $gitLfsOk = $false
}
if (-not $gitLfsOk) {
  throw 'git-lfs is still unavailable after bootstrap.'
}

& git lfs install --skip-repo | Out-Null

Emit-EnvFile -Path $EmitEnvFile -ExtraPaths $pathsToAdd
Write-Log '[OK] git/git-lfs are ready in local context.'
