param(
  [string]$RootDir,
  [string]$EmitEnvFile,
  [switch]$Quiet
)

$ErrorActionPreference = 'Stop'

if (-not $RootDir) {
  $RootDir = $PSScriptRoot
}

function Write-Log {
  param([string]$Message)
  if (-not $Quiet) {
    Write-Host $Message
  }
}

function Ensure-Dir {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path | Out-Null
  }
}

function Get-CommandPathOrNull {
  param([string]$Command)
  try {
    return (Get-Command $Command -ErrorAction Stop).Source
  } catch {
    return $null
  }
}

function Emit-EnvFile {
  param(
    [string]$Path,
    [string[]]$ExtraPaths
  )
  if (-not $Path) {
    return
  }

  $valid = @()
  foreach ($p in $ExtraPaths) {
    if ($p -and (Test-Path -LiteralPath $p)) {
      $valid += $p
    }
  }

  $envLine = if ($valid.Count -gt 0) {
    'set "PATH=' + (($valid -join ';') + ';%PATH%') + '"'
  } else {
    'rem no extra path entries required'
  }

  $content = @(
    '@echo off',
    'rem generated by ensure_portable_git_lfs.ps1',
    $envLine
  )

  $parent = Split-Path -Parent $Path
  if ($parent) {
    Ensure-Dir -Path $parent
  }
  Set-Content -Path $Path -Value $content -Encoding Ascii
}

$isWindows = $env:OS -eq 'Windows_NT'
$exeRoot = Join-Path $RootDir 'program\exe'
$localGitCmd = Join-Path $exeRoot 'git\cmd'
$localGitMingw = Join-Path $exeRoot 'git\mingw32\bin'
$localGitExe = Join-Path $localGitCmd 'git.exe'
$localLfsExe = Join-Path $localGitMingw 'git-lfs.exe'

if (-not $isWindows) {
  throw 'Linux/macOS detected. Please confirm whether to install/provide local git/git-lfs under program/exe before continuing.'
}

if (-not (Test-Path -LiteralPath $localGitExe)) {
  throw "Local git missing: $localGitExe"
}
if (-not (Test-Path -LiteralPath $localLfsExe)) {
  throw "Local git-lfs missing: $localLfsExe"
}

$pathsToAdd = @($localGitCmd, $localGitMingw)

if ($pathsToAdd.Count -gt 0) {
  $env:PATH = ($pathsToAdd -join ';') + ';' + $env:PATH
}

if (-not (Get-CommandPathOrNull -Command 'git')) {
  throw 'Local git is still unavailable after path injection.'
}

$gitLfsOk = $false
try {
  $null = & git lfs version
  $gitLfsOk = $true
} catch {
  $gitLfsOk = $false
}
if (-not $gitLfsOk) {
  throw 'Local git-lfs is still unavailable after path injection.'
}

& git lfs install --skip-repo | Out-Null

Emit-EnvFile -Path $EmitEnvFile -ExtraPaths $pathsToAdd
Write-Log '[OK] local git/git-lfs are ready in local context.'
